### ISSUE TITLE
AStar:get_map_index is wrong

### ISSUE THREAD

**Issue by huangzhentao** [bartontang/AStar-Lua#2]
> function AStar:get_map_index(row, col)
        local index = (row - 1) * self.mapRows+ col
        print("get_map_index(row, col) = "..index)
        return index
end

need change to

> function AStar:get_map_index(row, col)
        local index = (row - 1) * self.mapCols + col
        print("get_map_index(row, col) = "..index)
        return index
end

**Comment by bartontang** [comment]
Yes,you're right. Thanks very much. I have modified.
